// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5irxHrnb_ilKnoFvPEpBles-i_8VGYI0',
    appId: '1:840951361150:web:8b5ce0f7ae829a04e4322f',
    messagingSenderId: '840951361150',
    projectId: 'blood-donors-app-4366b',
    authDomain: 'blood-donors-app-4366b.firebaseapp.com',
    storageBucket: 'blood-donors-app-4366b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdaXcPahW-JNbnvBtNYCRsTu1vTCDpXCw',
    appId: '1:840951361150:android:37772b04dbb82395e4322f',
    messagingSenderId: '840951361150',
    projectId: 'blood-donors-app-4366b',
    storageBucket: 'blood-donors-app-4366b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIVj7ym0FcjUL_ahzRipS8QEGUJfIW-5A',
    appId: '1:840951361150:ios:938bae04550833c0e4322f',
    messagingSenderId: '840951361150',
    projectId: 'blood-donors-app-4366b',
    storageBucket: 'blood-donors-app-4366b.appspot.com',
    iosBundleId: 'com.example.bloodDonorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIVj7ym0FcjUL_ahzRipS8QEGUJfIW-5A',
    appId: '1:840951361150:ios:3c513a5c23f2509ae4322f',
    messagingSenderId: '840951361150',
    projectId: 'blood-donors-app-4366b',
    storageBucket: 'blood-donors-app-4366b.appspot.com',
    iosBundleId: 'com.example.bloodDonorApp.RunnerTests',
  );
}
